### PR TITLE
Add symbolic polynomial

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/soonho-tri/drake/14)

### CODE REVIEW

**Comment by soonho-tri** [comment]
Could you review the following files?

 - `monomial.h`
 - `monomial_util.h`
 - `symbolic_polynomial.h`

Here is the summary of the changes:

 - Moved code from `monomial.h` to `monomial_util.h` file. `monomial.h` only includes `Monomial` class and its related operations.
 - Make `Monomial` compatible with `Eigen::Matrix`.
 - Add `symbolic::Polynomial` class.

I still need to add more tests for the newly added code. I'd like to make sure that this is good at API levels (in header files).

---

Review status: 0 of 13 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/soonho-tri/drake/14#-:-KmTKdpmOV4D5YFNgQfS:b-8ex6tu)*

**Comment by hongkai-dai** [comment]
Reviewed 3 of 13 files at r1.
Review status: 3 of 13 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/common/monomial_util.h, line 102 at r1](https://reviewable.io:443/reviews/soonho-tri/drake/14#-KmTVh35o29UOMm2AooK:-KmTVh35o29UOMm2AooL:bv8aj74) ([raw file](https://github.com/soonho-tri/drake/blob/4bfc209b7efc5cb3739667d2017f320d19f88daf/drake/common/monomial_util.h#L102)):*
> ```objc
>  */
> template <typename MonomialOrder>
> void AddMonomialsOfDegreeN(const Variables& vars, int degree, const Monomial& b,
> ```

I feel this function probably belongs to some `internal` namespace? I cannot quite think of the case the user would call this function.

---

*[drake/common/monomial_util.h, line 178 at r1](https://reviewable.io:443/reviews/soonho-tri/drake/14#-KmTW6MgsghUTobaM3PO:-KmTW6MgsghUTobaM3PP:b-sew2jt) ([raw file](https://github.com/soonho-tri/drake/blob/4bfc209b7efc5cb3739667d2017f320d19f88daf/drake/common/monomial_util.h#L178)):*
> ```objc
>  * @pre @p degree is a non-negative integer.
>  */
> Eigen::Matrix<Monomial, Eigen::Dynamic, 1> MonomialBasis(const Variables& vars,
> ```

What is the difference between `ComputeMonomialBasis` and `MonomialBasis` functions? It feels that they have the same input arguments and functionality.

---

*[drake/common/symbolic_polynomial.h, line 50 at r1](https://reviewable.io:443/reviews/soonho-tri/drake/14#-KmTXYMoLNUS4nMzgsKE:-KmTXYMoLNUS4nMzgsKF:bto7nrk) ([raw file](https://github.com/soonho-tri/drake/blob/4bfc209b7efc5cb3739667d2017f320d19f88daf/drake/common/symbolic_polynomial.h#L50)):*
> ```objc
> 
>   Polynomial& operator+=(const Polynomial& p);
>   Polynomial& operator+=(const Monomial& m);
> ```

I feel there is some ambiguity to add/subtract/multiply two polynomials, when these two polynomials have different indeterminates. What would be the set of indeterminates after the binary operation? A documentation and some examples would be necessary. For example if we have polynomials `p1`, `p2` whose monomial_to_coefficient_map is
```
p1.map[x^2*y] = 3;
p1.map[x*y] = 2;
p2.map[x^2*z] = 1;
```
In this case, the indeterminates in `p1` are `x, y`; the indeterminates in `p2` are `x, z`. What would be the indeterminates in the added polynomial? Will it be `x, y, z` as the union of the indeterminates in each polynomial?

The problem becomes more worrisome if the indeterminates in one polynomial show up in the coefficient of the other, for example
```
p1.map[x^2*y] = z
p2.map[z] = x+y
```
in which `x,y` are the indeterminates of p1, `z` is the coefficient of `p1`. But in `p2`, the indeterminates is `z`, while the coefficients are `x, y`.  Probably for this case, we should add some code to check if the indeterminates in one polynomial does not show up in the coefficients of the other.

---

*[drake/common/symbolic_polynomial.h, line 69 at r1](https://reviewable.io:443/reviews/soonho-tri/drake/14#-KmT_8oPuc4wRurvA0YB:-KmT_8oPuc4wRurvA0YC:bnnoc7a) ([raw file](https://github.com/soonho-tri/drake/blob/4bfc209b7efc5cb3739667d2017f320d19f88daf/drake/common/symbolic_polynomial.h#L69)):*
> ```objc
>  private:
>   /// Add (coeff * m) to this polynomial.
>   Polynomial& Add(const double coeff, const Monomial& m);
> ```

`const double` -> `double`? Also why the `coeff` is not `const symbolic::Expression`?

---

*[drake/common/symbolic_polynomial.h, line 94 at r1](https://reviewable.io:443/reviews/soonho-tri/drake/14#-KmT_SZ0aT8Sn5DAMO6Y:-KmT_SZ0aT8Sn5DAMO6Z:b-lbfnsn) ([raw file](https://github.com/soonho-tri/drake/blob/4bfc209b7efc5cb3739667d2017f320d19f88daf/drake/common/symbolic_polynomial.h#L94)):*
> ```objc
> Polynomial operator*(Polynomial p, const Monomial& m);
> Polynomial operator*(const Monomial& m, Polynomial p);
> Polynomial operator*(int n, Polynomial p);
> ```

Why `int` here instead of `double`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/soonho-tri/drake/14)*

**Comment by hongkai-dai** [comment]
Reviewed 2 of 13 files at r1.
Review status: 5 of 13 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/common/monomial.cc, line 253 at r1](https://reviewable.io:443/reviews/soonho-tri/drake/14#-KmTaPUvbAotwTJOELcx:-KmTaPUvbAotwTJOELcy:b-7g8hlk) ([raw file](https://github.com/soonho-tri/drake/blob/4bfc209b7efc5cb3739667d2017f320d19f88daf/drake/common/monomial.cc#L253)):*
> ```cpp
>   }
>   for (++it; it != m.powers_.end(); ++it) {
>     out << " + ";
> ```

`+` -> `*`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/soonho-tri/drake/14)*

**Comment by moritzkuhne** [comment]
Review status: 5 of 13 files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/common/monomial.h, line 42 at r1](https://reviewable.io:443/reviews/soonho-tri/drake/14#-KmTgCkwW6sOOwsGLLzX:-KmTgCkysWHZ7-9qChn7:bm2y7xk) ([raw file](https://github.com/soonho-tri/drake/blob/4bfc209b7efc5cb3739667d2017f320d19f88daf/drake/common/monomial.h#L42)):*
> ```objc
>   /** Constructs a Monomial from @p var. */
>   explicit Monomial(const Variable& var);
> ```

For my understanding. Why do we enforce `explicit` in `explicit Monomial(const Variable& var);` but not in ` Monomial(const Variable& var, int exponent);`? 

---

*[drake/common/monomial_util.h, line 178 at r1](https://reviewable.io:443/reviews/soonho-tri/drake/14#-KmTW6MgsghUTobaM3PO:-KmTjDY6ZurlLJQl9_TJ:b2ie2zf) ([raw file](https://github.com/soonho-tri/drake/blob/4bfc209b7efc5cb3739667d2017f320d19f88daf/drake/common/monomial_util.h#L178)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

What is the difference between `ComputeMonomialBasis` and `MonomialBasis` functions? It feels that they have the same input arguments and functionality.
</blockquote></details>

it seams like there is something wrong: `Eigen::Matrix<Monomial, Eigen::Dynamic, 1> MonomialBasis(const Variables& vars,` ... Maybe an artifact from merging?

---

*[drake/common/symbolic_polynomial.h, line 50 at r1](https://reviewable.io:443/reviews/soonho-tri/drake/14#-KmTXYMoLNUS4nMzgsKE:-KmTjy3RFP6RScZ_GMgR:bb6mt9b) ([raw file](https://github.com/soonho-tri/drake/blob/4bfc209b7efc5cb3739667d2017f320d19f88daf/drake/common/symbolic_polynomial.h#L50)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I feel there is some ambiguity to add/subtract/multiply two polynomials, when these two polynomials have different indeterminates. What would be the set of indeterminates after the binary operation? A documentation and some examples would be necessary. For example if we have polynomials `p1`, `p2` whose monomial_to_coefficient_map is
```
p1.map[x^2*y] = 3;
p1.map[x*y] = 2;
p2.map[x^2*z] = 1;
```
In this case, the indeterminates in `p1` are `x, y`; the indeterminates in `p2` are `x, z`. What would be the indeterminates in the added polynomial? Will it be `x, y, z` as the union of the indeterminates in each polynomial?

The problem becomes more worrisome if the indeterminates in one polynomial show up in the coefficient of the other, for example
```
p1.map[x^2*y] = z
p2.map[z] = x+y
```
in which `x,y` are the indeterminates of p1, `z` is the coefficient of `p1`. But in `p2`, the indeterminates is `z`, while the coefficients are `x, y`.  Probably for this case, we should add some code to check if the indeterminates in one polynomial does not show up in the coefficients of the other.
</blockquote></details>

:+1:

---

*[drake/common/symbolic_polynomial.h, line 99 at r1](https://reviewable.io:443/reviews/soonho-tri/drake/14#-KmTkzYaH1LTRDheLGct:-KmTkzYbSE-DfNsloGNx:b-hgifbp) ([raw file](https://github.com/soonho-tri/drake/blob/4bfc209b7efc5cb3739667d2017f320d19f88daf/drake/common/symbolic_polynomial.h#L99)):*
> ```objc
> /// Returns polynomial @p rasied to @p n.
> Polynomial pow(Polynomial p, int n);
> ```

Maybe we could add a TODO here. We should move `Expression operator+(Variable, Variable)` and `Expression pow(Variable,int)` from `symbolic::Expression` to `symbolic_Polynomial` and change there return types. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/soonho-tri/drake/14)*

**Comment by soonho-tri** [comment]
Review status: 1 of 19 files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/common/monomial.cc, line 253 at r1](https://reviewable.io:443/reviews/soonho-tri/drake/14#-KmTaPUvbAotwTJOELcx:-KmU-FnMFj2VgvRG_sTl:b-896fix) ([raw file](https://github.com/soonho-tri/drake/blob/4bfc209b7efc5cb3739667d2017f320d19f88daf/drake/common/monomial.cc#L253)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

`+` -> `*`?
</blockquote></details>

Done.

---

*[drake/common/monomial.h, line 42 at r1](https://reviewable.io:443/reviews/soonho-tri/drake/14#-KmTgCkwW6sOOwsGLLzX:-KmU-Nczt73EZGtKpGQt:biq3ve0) ([raw file](https://github.com/soonho-tri/drake/blob/4bfc209b7efc5cb3739667d2017f320d19f88daf/drake/common/monomial.h#L42)):*
<details><summary><i>Previously, FischerGundlach wrote…</i></summary><blockquote>

For my understanding. Why do we enforce `explicit` in `explicit Monomial(const Variable& var);` but not in ` Monomial(const Variable& var, int exponent);`? 
</blockquote></details>

`explicit` keyword is only meaningful with constructors with a single argument. https://stackoverflow.com/questions/121162/what-does-the-explicit-keyword-mean has a good explanation about it.

---

*[drake/common/monomial_util.h, line 102 at r1](https://reviewable.io:443/reviews/soonho-tri/drake/14#-KmTVh35o29UOMm2AooK:-KmTein8sjqYyjGJ3iC6:b-896fix) ([raw file](https://github.com/soonho-tri/drake/blob/4bfc209b7efc5cb3739667d2017f320d19f88daf/drake/common/monomial_util.h#L102)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I feel this function probably belongs to some `internal` namespace? I cannot quite think of the case the user would call this function.
</blockquote></details>

Done.

---

*[drake/common/monomial_util.h, line 178 at r1](https://reviewable.io:443/reviews/soonho-tri/drake/14#-KmTW6MgsghUTobaM3PO:-KmTgqb3XEUcm9YpS5T8:b-56cd2p) ([raw file](https://github.com/soonho-tri/drake/blob/4bfc209b7efc5cb3739667d2017f320d19f88daf/drake/common/monomial_util.h#L178)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

What is the difference between `ComputeMonomialBasis` and `MonomialBasis` functions? It feels that they have the same input arguments and functionality.
</blockquote></details>

Done. (Moved into `internal` namespace)

This is the function used by the following functions (which we expect users to use):
```c++
Eigen::Matrix<Monomial, Eigen::Dynamic, 1> MonomialBasis(const Variables& vars,
                                                         int degree);

template <int n, int degree>
Eigen::Matrix<Monomial, NChooseK(n + degree, degree), 1> MonomialBasis(
    const Variables& vars);
```

---

*[drake/common/symbolic_polynomial.h, line 50 at r1](https://reviewable.io:443/reviews/soonho-tri/drake/14#-KmTXYMoLNUS4nMzgsKE:-KmThH-i0GENHixtpBL2:bjgdqmz) ([raw file](https://github.com/soonho-tri/drake/blob/4bfc209b7efc5cb3739667d2017f320d19f88daf/drake/common/symbolic_polynomial.h#L50)):*
<details><summary><i>Previously, FischerGundlach wrote…</i></summary><blockquote>

:+1:
</blockquote></details>

I had the same concern as well. That's why we have the private `CheckInvariant()` method below. I'll add more documentation this evening.

For now, `Polynomial` class has a set of indeterminates as a member to make this check easier. I'm thinking if I can eliminate this to make things simpler. I'll think more about this one.

---

*[drake/common/symbolic_polynomial.h, line 69 at r1](https://reviewable.io:443/reviews/soonho-tri/drake/14#-KmT_8oPuc4wRurvA0YB:-KmTiSKJliOPn0e0WCJQ:bs7wumb) ([raw file](https://github.com/soonho-tri/drake/blob/4bfc209b7efc5cb3739667d2017f320d19f88daf/drake/common/symbolic_polynomial.h#L69)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

`const double` -> `double`? Also why the `coeff` is not `const symbolic::Expression`?
</blockquote></details>

Done.

---

*[drake/common/symbolic_polynomial.h, line 94 at r1](https://reviewable.io:443/reviews/soonho-tri/drake/14#-KmT_SZ0aT8Sn5DAMO6Y:-KmTzyOHoPrdMxHDaUWI:b-896fix) ([raw file](https://github.com/soonho-tri/drake/blob/4bfc209b7efc5cb3739667d2017f320d19f88daf/drake/common/symbolic_polynomial.h#L94)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Why `int` here instead of `double`?
</blockquote></details>

Done.

---

*[drake/common/symbolic_polynomial.h, line 99 at r1](https://reviewable.io:443/reviews/soonho-tri/drake/14#-KmTkzYaH1LTRDheLGct:-KmU-fEB96iJJj5aT-LR:b-6q1bd9) ([raw file](https://github.com/soonho-tri/drake/blob/4bfc209b7efc5cb3739667d2017f320d19f88daf/drake/common/symbolic_polynomial.h#L99)):*
<details><summary><i>Previously, FischerGundlach wrote…</i></summary><blockquote>

Maybe we could add a TODO here. We should move `Expression operator+(Variable, Variable)` and `Expression pow(Variable,int)` from `symbolic::Expression` to `symbolic_Polynomial` and change there return types. 
</blockquote></details>

I think it's better to keep the current hierarchy of `Variable` - `Expression` - `Formula`. 

1. To have `+ : Variable x Variable -> Polynomial`, we can do `Polynomial(v_1 + v_2)`. It's a bit verbose, but I think it's not too bad.

2. For now, we have `pow : Variable x int -> Expression`.  One can argue that it should be `pow : Variable x int -> Polynomial` while another can say that it should be `pow : Variable x int -> Monomial`. FYI, the current implementation asks users to write `Monomial(v, n)` to denote `pow(v, n)` in `Monomial`. To represent it as a `Polynomial`, one has to write `Polynomial(Monomial(v, n))`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/soonho-tri/drake/14)*

**Comment by hongkai-dai** [comment]
Review status: 1 of 19 files reviewed at latest revision, 6 unresolved discussions.

---

*[drake/common/symbolic_polynomial.h, line 50 at r1](https://reviewable.io:443/reviews/soonho-tri/drake/14#-KmTXYMoLNUS4nMzgsKE:-KmURcR5HSfTHFsJyiQP:btaxtxk) ([raw file](https://github.com/soonho-tri/drake/blob/4bfc209b7efc5cb3739667d2017f320d19f88daf/drake/common/symbolic_polynomial.h#L50)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I had the same concern as well. That's why we have the private `CheckInvariant()` method below. I'll add more documentation this evening.

For now, `Polynomial` class has a set of indeterminates as a member to make this check easier. I'm thinking if I can eliminate this to make things simpler. I'll think more about this one.
</blockquote></details>

I feel in the constructor of the polynomial, we should check if the variables in the coefficients overlaps with the indeterminates, and throw an error if that happens.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/soonho-tri/drake/14)*

**Comment by soonho-tri** [comment]
Review status: 1 of 19 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/common/symbolic_polynomial.h, line 50 at r1](https://reviewable.io:443/reviews/soonho-tri/drake/14#-KmTXYMoLNUS4nMzgsKE:-KmUS7DxFCWDoRHxy-fK:buvo5aj) ([raw file](https://github.com/soonho-tri/drake/blob/4bfc209b7efc5cb3739667d2017f320d19f88daf/drake/common/symbolic_polynomial.h#L50)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I feel in the constructor of the polynomial, we should check if the variables in the coefficients overlaps with the indeterminates, and throw an error if that happens.
</blockquote></details>

Yes, that's the case. In addition to that, we need to check the invariant in all non-const member functions (unless it's not needed clearly).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/soonho-tri/drake/14)*

**Comment by hongkai-dai** [comment]
Reviewed 1 of 13 files at r1, 4 of 13 files at r2.
Review status: 6 of 19 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/common/symbolic_polynomial.cc, line 205 at r2](https://reviewable.io:443/reviews/soonho-tri/drake/14#-KmUT4yavS7LPmhW4YrC:-KmUT4yavS7LPmhW4YrD:b-udynli) ([raw file](https://github.com/soonho-tri/drake/blob/abf55b962840e98e1f76011ff5be04c00ea8c0e8/drake/common/symbolic_polynomial.cc#L205)):*
> ```cpp
>     } else {
>       // The entry, coeff * m in p, exists in this polynomial.
>       if (is_zero(it->second + coeff)) {
> ```

Do we guarantee that the coefficients have been expanded? For non-expanded expression, `is_zero` probably does not give the best answer. This is probably not a big deal, since `((a+b)^2 - (a^2 + 2 * a*b + b^2)) * x` can still exist in the polynomial map.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/soonho-tri/drake/14)*

**Comment by hongkai-dai** [comment]
Reviewed 1 of 13 files at r1.
Review status: 6 of 19 files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/common/symbolic_polynomial.cc, line 231 at r1](https://reviewable.io:443/reviews/soonho-tri/drake/14#-KmUV0sfi40RBYm3gUjV:-KmUV0sfi40RBYm3gUjW:b-1yyabt) ([raw file](https://github.com/soonho-tri/drake/blob/4bfc209b7efc5cb3739667d2017f320d19f88daf/drake/common/symbolic_polynomial.cc#L231)):*
> ```cpp
>   //   + ...
>   //   + (c₁₁ * m₁₁ + ... + c₁ₙ * m₁ₙ) * c₂ₘ * m₂ₘ
>   // TODO(soonho-tri): Optimize this by not relying on ToExpression() method.
> ```

May I volunteer to work on this?

---

*[drake/common/symbolic_polynomial.cc, line 276 at r1](https://reviewable.io:443/reviews/soonho-tri/drake/14#-KmUVJBanAUsE4UiLIBf:-KmUVJBbMBKxY8zukWnj:bpat8gt) ([raw file](https://github.com/soonho-tri/drake/blob/4bfc209b7efc5cb3739667d2017f320d19f88daf/drake/common/symbolic_polynomial.cc#L276)):*
> ```cpp
>        p.monomial_to_coefficient_map_) {
>     const Expression& coeff{item.second};
>     ret = ret && (coeff == 0.0);
> ```

For my educational purpose, what is the difference of doing `coeff == 0.0` and `is_zero(coeff)`?

---

*[drake/common/symbolic_polynomial.cc, line 281 at r1](https://reviewable.io:443/reviews/soonho-tri/drake/14#-KmUVVULrBrMtm8fyrWz:-KmUVVULrBrMtm8fyrX-:b-4uako4) ([raw file](https://github.com/soonho-tri/drake/blob/4bfc209b7efc5cb3739667d2017f320d19f88daf/drake/common/symbolic_polynomial.cc#L281)):*
> ```cpp
> }
> 
> Polynomial& Polynomial::Add(const double coeff, const Monomial& m) {
> ```

`const double` -> `const symbolic::Expression&`? 

---

*[drake/common/symbolic_polynomial.h, line 50 at r1](https://reviewable.io:443/reviews/soonho-tri/drake/14#-KmTXYMoLNUS4nMzgsKE:-KmUU6SlewGXuVEBGEE8:b-f3vet1) ([raw file](https://github.com/soonho-tri/drake/blob/4bfc209b7efc5cb3739667d2017f320d19f88daf/drake/common/symbolic_polynomial.h#L50)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Yes, that's the case. In addition to that, we need to check the invariant in all non-const member functions (unless it's not needed clearly).
</blockquote></details>

Checking the invariant sounds good! Maybe we also keep a private member `coefficient_variables` to store all the variables appeared in the coefficients?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/soonho-tri/drake/14)*

**Comment by soonho-tri** [comment]
Review status: 5 of 22 files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/common/symbolic_polynomial.cc, line 231 at r1](https://reviewable.io:443/reviews/soonho-tri/drake/14#-KmUV0sfi40RBYm3gUjV:-KmWs7NrjBCDoa-Zv046:b-80tlqx) ([raw file](https://github.com/soonho-tri/drake/blob/4bfc209b7efc5cb3739667d2017f320d19f88daf/drake/common/symbolic_polynomial.cc#L231)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

May I volunteer to work on this?
</blockquote></details>

Sure!

---

*[drake/common/symbolic_polynomial.cc, line 276 at r1](https://reviewable.io:443/reviews/soonho-tri/drake/14#-KmUVJBanAUsE4UiLIBf:-KmWdM1Gt2c49NB2wkNL:b-maqblg) ([raw file](https://github.com/soonho-tri/drake/blob/4bfc209b7efc5cb3739667d2017f320d19f88daf/drake/common/symbolic_polynomial.cc#L276)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

For my educational purpose, what is the difference of doing `coeff == 0.0` and `is_zero(coeff)`?
</blockquote></details>

Good question! Please check the following signatures, esp their return types.
```
bool is_zero(const Expression& e);
Formula operator==(const Expression& e1, const Expression& e2);
```

`is_zero` checks if `e` is `Expression::Zero()`. It uses structural equality and returns `bool`. For example, for a variable `x`, `is_zero(x)` will return `false`.

`operator==` captures an equality constraint and forms a corresponding symbolic formula. With the same example, `x == 0` returns a symbolic Formula which will be evaluated to `true` only if `x` gets `0`.

---

*[drake/common/symbolic_polynomial.cc, line 281 at r1](https://reviewable.io:443/reviews/soonho-tri/drake/14#-KmUVVULrBrMtm8fyrWz:-KmWeWxiOfWL1aaLK9QO:biyivu1) ([raw file](https://github.com/soonho-tri/drake/blob/4bfc209b7efc5cb3739667d2017f320d19f88daf/drake/common/symbolic_polynomial.cc#L281)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

`const double` -> `const symbolic::Expression&`? 
</blockquote></details>

I think it's already `const symbolic::Expression&` here?

---

*[drake/common/symbolic_polynomial.cc, line 205 at r2](https://reviewable.io:443/reviews/soonho-tri/drake/14#-KmUT4yavS7LPmhW4YrC:-KmWt0HkLWMPBTw5vMqz:b-m216v7) ([raw file](https://github.com/soonho-tri/drake/blob/abf55b962840e98e1f76011ff5be04c00ea8c0e8/drake/common/symbolic_polynomial.cc#L205)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Do we guarantee that the coefficients have been expanded? For non-expanded expression, `is_zero` probably does not give the best answer. This is probably not a big deal, since `((a+b)^2 - (a^2 + 2 * a*b + b^2)) * x` can still exist in the polynomial map.
</blockquote></details>

Nice!

I've changed the code to use `.Expand()`. I also added comments explaining why we need it (with your example).

---

*[drake/common/symbolic_polynomial.h, line 50 at r1](https://reviewable.io:443/reviews/soonho-tri/drake/14#-KmTXYMoLNUS4nMzgsKE:-KmWsDTqOITgY7nZICkM:bniymrf) ([raw file](https://github.com/soonho-tri/drake/blob/4bfc209b7efc5cb3739667d2017f320d19f88daf/drake/common/symbolic_polynomial.h#L50)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Checking the invariant sounds good! Maybe we also keep a private member `coefficient_variables` to store all the variables appeared in the coefficients?
</blockquote></details>

I actually moved the other direction. Now, `Polynomial` class only have a single member field, a map from Monomial to Expression.

It does have two methods:
```c++
  /// Returns the indeterminates of this polynomial.
  Variables indeterminates() const;

  /// Returns the decision variables of this polynomial.
  Variables decision_variables() const;
```
which we use in `CheckInvariant()`.

What we can get from this design is simplicity, we don't need to maintain two `Variables` and maintain the invariants. Probably downside of this approach is the fact that we need to compute the two sets every time they are needed. I'll revisit them if it turns out to be a problem.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/soonho-tri/drake/14)*

**Comment by soonho-tri** [comment]
FYI, I'll close and merge this PR into `master` as soon as all the discussions here are resolved.

---

Review status: 5 of 22 files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/soonho-tri/drake/14#-:-KmXBeLpusBPf5Sohm7A:b-12isf4)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Reviewed 1 of 7 files at r3.
Review status: 6 of 22 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/common/symbolic_polynomial.cc, line 276 at r1](https://reviewable.io:443/reviews/soonho-tri/drake/14#-KmUVJBanAUsE4UiLIBf:-KmXE0-NKCyPppdpEeX_:b9tf8bl) ([raw file](https://github.com/soonho-tri/drake/blob/4bfc209b7efc5cb3739667d2017f320d19f88daf/drake/common/symbolic_polynomial.cc#L276)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

Good question! Please check the following signatures, esp their return types.
```
bool is_zero(const Expression& e);
Formula operator==(const Expression& e1, const Expression& e2);
```

`is_zero` checks if `e` is `Expression::Zero()`. It uses structural equality and returns `bool`. For example, for a variable `x`, `is_zero(x)` will return `false`.

`operator==` captures an equality constraint and forms a corresponding symbolic formula. With the same example, `x == 0` returns a symbolic Formula which will be evaluated to `true` only if `x` gets `0`.

</blockquote></details>

Thanks a lot for the clear explanation!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/soonho-tri/drake/14#-:-KmXEPfbw3lOJfSdZ6Vr:bnfp4nl)*

**Pull request merged**
