### PR TITLE
Polynomial product

### PR DESCRIPTION
**Pull request by hongkai-dai**
This change is [Reviewable](https://reviewable.io/reviews/soonho-tri/drake/19)

### CODE REVIEW

**Comment by soonho-tri** [comment]
Thank you Hongkai! 
:lgtm: (aside a BTW)

---

Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/symbolic_polynomial.cc, line 282 at r1](https://reviewable.io:443/reviews/soonho-tri/drake/19#-Kmcl4GZkHsjOU03ljQ8:-Kmcl4GZkHsjOU03ljQ9:btlh8se) ([raw file](https://github.com/soonho-tri/drake/blob/4ef61509959079f34f33c5bf1035637793de6a0b/drake/common/symbolic_polynomial.cc#L282)):*
> ```cpp
>     }
>   }
>   monomial_to_coefficient_map_ = new_map;
> ```

BTW, I think we can do to steal `new_map`:
```c++
 monomial_to_coefficient_map_ = std::move(new_map);
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/soonho-tri/drake/19#-:-KmclHCqwywL38G9iJLx:b-80278t)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/soonho-tri/drake/19)*

**Comment by hongkai-dai** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/common/symbolic_polynomial.cc, line 282 at r1](https://reviewable.io:443/reviews/soonho-tri/drake/19#-Kmcl4GZkHsjOU03ljQ8:-KmcnZ3yKazOjzO3ExUh:b-896fix) ([raw file](https://github.com/soonho-tri/drake/blob/4ef61509959079f34f33c5bf1035637793de6a0b/drake/common/symbolic_polynomial.cc#L282)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

BTW, I think we can do to steal `new_map`:
```c++
 monomial_to_coefficient_map_ = std::move(new_map);
```

</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/soonho-tri/drake/19)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/soonho-tri/drake/19#-:-KmcsbtwM0y-xh_dPZhJ:bnfp4nl)*

**Pull request merged**
