### PR TITLE
Add AddSosConstraint(const symbolic::Expression& e)

### PR DESCRIPTION
**Pull request by soonho-tri**
This is a small PR adding `AddSosConstraint(const symbolic::Expression& e)`. I think it should be useful for beginners who do not even want to know about `symbolic::Polynomial`.

---
This change is [Reviewable](https://reviewable.io/reviews/soonho-tri/drake/17)

### CODE REVIEW

**Comment by moritzkuhne** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/soonho-tri/drake/17#-:-KmcXWZ692WGSyRC-G6K:bnfp4nl)*

**Comment by hongkai-dai** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/mathematical_program.cc, line 677 at r1](https://reviewable.io:443/reviews/soonho-tri/drake/17#-Kmce2zUhHg-KelDfZ4k:-Kmce2zVQrsMCfzHpx5w:bsm5uhg) ([raw file](https://github.com/soonho-tri/drake/blob/56667f14902d199e8d46b041f6442c128cad33c1/drake/solvers/mathematical_program.cc#L677)):*
> ```cpp
> pair<Binding<PositiveSemidefiniteConstraint>, Binding<LinearEqualityConstraint>>
> MathematicalProgram::AddSosConstraint(const symbolic::Expression& e) {
>   return AddSosConstraint(symbolic::Polynomial{e});
> ```

I think we should do 
```C++
return AddSosConstraint(symbolic::Polynomial{e, indeterminates_});
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/soonho-tri/drake/17)*

**Comment by soonho-tri** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/solvers/mathematical_program.cc, line 677 at r1](https://reviewable.io:443/reviews/soonho-tri/drake/17#-Kmce2zUhHg-KelDfZ4k:-KmcgsgAm8RhxyUnWA5u:boyexb3) ([raw file](https://github.com/soonho-tri/drake/blob/56667f14902d199e8d46b041f6442c128cad33c1/drake/solvers/mathematical_program.cc#L677)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I think we should do 
```C++
return AddSosConstraint(symbolic::Polynomial{e, indeterminates_});
```
</blockquote></details>

Done. Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/soonho-tri/drake/17)*

**Comment by hongkai-dai** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/soonho-tri/drake/17#-:-KmchVcqUYcw4PjBdjLa:bnfp4nl)*

**Pull request merged**
