### PR TITLE
Add NewFreePolynomial, NewSosPolynomial, AddSosConstraint

### PR DESCRIPTION
**Pull request by soonho-tri**
This change is [Reviewable](https://reviewable.io/reviews/soonho-tri/drake/16)

### CODE REVIEW

**Comment by moritzkuhne** [comment]
Review status: 0 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/solvers/BUILD, line 176 at r2](https://reviewable.io:443/reviews/soonho-tri/drake/16#-KmaqZIGCxoRCBvRtI9h:-KmaqZIHM-tT55mw77_l:b-lzargv) ([raw file](https://github.com/soonho-tri/drake/blob/e089f6a64a51e4219e632fbc6742640fabc97b90/drake/solvers/BUILD#L176)):*
> ```Python
>         "//drake/common:polynomial",
>         "//drake/common:symbolic",
>         "//drake/common:symbolic_polynomial",        
> ```

Where do these spaces/dots  `"//drake/common:symbolic_polynomial",········` come from?

---

*[drake/solvers/CMakeLists.txt, line 6 at r2](https://reviewable.io:443/reviews/soonho-tri/drake/16#-Kmaqu6QuqSXOtA3tGxt:-Kmaqu6RaSGjBR0Z-M5F:b-y3h7g) ([raw file](https://github.com/soonho-tri/drake/blob/e089f6a64a51e4219e632fbc6742640fabc97b90/drake/solvers/CMakeLists.txt#L6)):*
> ```CMake
>         drakeOptimization
>         drakeCommon)
> ```

Sorry, this one needs to go. It is one of my artifacts. I have an executable where I check that everything compiles. Sorry for that.   

---

*[drake/solvers/mathematical_program.cc, line 213 at r2](https://reviewable.io:443/reviews/soonho-tri/drake/16#-Kmay_s5UC0eKjb-4QUY:-Kmay_s7TB8BVLVpQMlL:b-m7v4al) ([raw file](https://github.com/soonho-tri/drake/blob/e089f6a64a51e4219e632fbc6742640fabc97b90/drake/solvers/mathematical_program.cc#L213)):*
> ```cpp
> pair<drake::symbolic::Polynomial, VectorXDecisionVariable>
> MathematicalProgram::NewFreePolynomial(const Variables& indeterminates,
>                                        const int degree) {
> ```

remove the `const` in `...,const int degree)`? Does it actually do anything without `&` or is it a safety mechanism such that you do not overwrite it somewhere in the function?

---

*[drake/solvers/mathematical_program.cc, line 706 at r2](https://reviewable.io:443/reviews/soonho-tri/drake/16#-KmaxT_G9gkebMFj8dT3:-KmaxT_HMpa2ReogRrf-:b-uciy8q) ([raw file](https://github.com/soonho-tri/drake/blob/e089f6a64a51e4219e632fbc6742640fabc97b90/drake/solvers/mathematical_program.cc#L706)):*
> ```cpp
>     oss << var
>         << " is not a indeterminate in the mathematical program, "
>            "when calling GetSolution.\n";
> ```

is not aN indeterminate

---

*[drake/solvers/mathematical_program.h, line 1926 at r2](https://reviewable.io:443/reviews/soonho-tri/drake/16#-KmazemTDEpbMBfPyRJl:-KmazemUUOZD2-33Fbau:bpdavyi) ([raw file](https://github.com/soonho-tri/drake/blob/e089f6a64a51e4219e632fbc6742640fabc97b90/drake/solvers/mathematical_program.h#L1926)):*
> ```objc
>    * (@see MathematicalProgramm::NewFreePolynomial) poly is constraint to be a
>    * SOS.
>    */
> ```

This is misleading (even for me, that I wrote it). I will change it in a documentation PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/soonho-tri/drake/16)*

**Comment by soonho-tri** [comment]
Review status: 0 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[drake/solvers/BUILD, line 176 at r2](https://reviewable.io:443/reviews/soonho-tri/drake/16#-KmaqZIGCxoRCBvRtI9h:-Kmb1BvMpkFfHK4X6dA6:bzdq0vv) ([raw file](https://github.com/soonho-tri/drake/blob/e089f6a64a51e4219e632fbc6742640fabc97b90/drake/solvers/BUILD#L176)):*
<details><summary><i>Previously, FischerGundlach wrote…</i></summary><blockquote>

Where do these spaces/dots  `"//drake/common:symbolic_polynomial",········` come from?
</blockquote></details>

Done.

It means that there are trailing whitespaces (which are usually considered not good ones).

---

*[drake/solvers/mathematical_program.cc, line 213 at r2](https://reviewable.io:443/reviews/soonho-tri/drake/16#-Kmay_s5UC0eKjb-4QUY:-Kmb1dHzYUg2WM43AoyZ:b-qstabu) ([raw file](https://github.com/soonho-tri/drake/blob/e089f6a64a51e4219e632fbc6742640fabc97b90/drake/solvers/mathematical_program.cc#L213)):*
<details><summary><i>Previously, FischerGundlach wrote…</i></summary><blockquote>

remove the `const` in `...,const int degree)`? Does it actually do anything without `&` or is it a safety mechanism such that you do not overwrite it somewhere in the function?
</blockquote></details>

It's for the safety.

According to the in-house code-style guide, we do not allow `const int` in a header file, but we can still have them in a definition (in a `.cc`). For more information, please find a bullet starting with "For the Use of const style rule" in http://drake.mit.edu/code_style_guide.html#clarifications.

---

*[drake/solvers/mathematical_program.cc, line 706 at r2](https://reviewable.io:443/reviews/soonho-tri/drake/16#-KmaxT_G9gkebMFj8dT3:-Kmb2B-Ixgo3XUbGwRBM:b-896fix) ([raw file](https://github.com/soonho-tri/drake/blob/e089f6a64a51e4219e632fbc6742640fabc97b90/drake/solvers/mathematical_program.cc#L706)):*
<details><summary><i>Previously, FischerGundlach wrote…</i></summary><blockquote>

is not aN indeterminate
</blockquote></details>

Done.

---

*[drake/solvers/mathematical_program.h, line 1926 at r2](https://reviewable.io:443/reviews/soonho-tri/drake/16#-KmazemTDEpbMBfPyRJl:-Kmb2J61B5oDWXCXCANv:bio389z) ([raw file](https://github.com/soonho-tri/drake/blob/e089f6a64a51e4219e632fbc6742640fabc97b90/drake/solvers/mathematical_program.h#L1926)):*
Done.

>  I will change it in a documentation PR.

SGTM!

---

*[drake/solvers/CMakeLists.txt, line 6 at r2](https://reviewable.io:443/reviews/soonho-tri/drake/16#-Kmaqu6QuqSXOtA3tGxt:-Kmb1TxRKxgSk4OJzeDx:b-896fix) ([raw file](https://github.com/soonho-tri/drake/blob/e089f6a64a51e4219e632fbc6742640fabc97b90/drake/solvers/CMakeLists.txt#L6)):*
<details><summary><i>Previously, FischerGundlach wrote…</i></summary><blockquote>

Sorry, this one needs to go. It is one of my artifacts. I have an executable where I check that everything compiles. Sorry for that.   
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/soonho-tri/drake/16)*

**Comment by hongkai-dai** [comment]
checkpoint

---

Reviewed 3 of 5 files at r2, 1 of 4 files at r3.
Review status: 4 of 7 files reviewed at latest revision, 10 unresolved discussions.

---

*[drake/common/symbolic_polynomial.h, line 48 at r3](https://reviewable.io:443/reviews/soonho-tri/drake/16#-KmbALTJXbOk27La8gIk:-KmbALTJXbOk27La8gIl:b-zhxq7z) ([raw file](https://github.com/soonho-tri/drake/blob/9e9768e39a554e34316b6f8d155d4d083404fda7/drake/common/symbolic_polynomial.h#L48)):*
> ```objc
> 
>   /// Returns the total degree of this polynomial.
>   int Degree() const;
> ```

Add a TODO here, that we will implement `int Degree(const Variables& vars)`, which returns the degrees for the  specified variables?

---

*[drake/common/symbolic_polynomial.h, line 111 at r3](https://reviewable.io:443/reviews/soonho-tri/drake/16#-KmbAtc9ERGfc51RlkrN:-KmbAtc9ERGfc51RlkrO:b27v15g) ([raw file](https://github.com/soonho-tri/drake/blob/9e9768e39a554e34316b6f8d155d4d083404fda7/drake/common/symbolic_polynomial.h#L111)):*
> ```objc
> Polynomial operator*(Polynomial p, const Variable& v);
> Polynomial operator*(const Variable& v, Polynomial p);
> Polynomial operator*(const Variable& v, const Monomial& m);
> ```

variable * monomial should return a monomial instead of a polynomial?

---

*[drake/solvers/mathematical_program.cc, line 240 at r3](https://reviewable.io:443/reviews/soonho-tri/drake/16#-KmbDL9OSEElz99leDU0:-KmbDL9OSEElz99leDU1:b852pxa) ([raw file](https://github.com/soonho-tri/drake/blob/9e9768e39a554e34316b6f8d155d4d083404fda7/drake/solvers/mathematical_program.cc#L240)):*
> ```cpp
> MathematicalProgram::NewSosPolynomial(const Variables& indeterminates,
>                                       const int degree) {
>   const drake::VectorX<symbolic::Monomial> X{
> ```

Capital `X` would mean a matrix to mean, maybe use lower case `x`？

---

*[drake/solvers/mathematical_program.h, line 653 at r3](https://reviewable.io:443/reviews/soonho-tri/drake/16#-KmbBkqAoA-6kiJm1hEc:-KmbBkqAoA-6kiJm1hEd:bs0wnbn) ([raw file](https://github.com/soonho-tri/drake/blob/9e9768e39a554e34316b6f8d155d4d083404fda7/drake/solvers/mathematical_program.h#L653)):*
> ```objc
>   // TODO(FischerGundlach) Add documentation incl. an example.
>   std::pair<symbolic::Polynomial, VectorXDecisionVariable> NewFreePolynomial(
>       const VectorXIndeterminate& indeterminates, int degree);
> ```

The difference between `symbolic::Variables` and `VectorXIndeterminate` are
1. In VectorXIndeterminate, the user can define an order.
2. In VectorXIndeterminate, there can be duplicated entries.
My feeling is that we do not care about the order used in VectorXIndeterminate, and we want to avoid duplicated entries in `indeterminates`, so maybe we only keep the API with `symbolic::Variables`?

---

*[drake/solvers/mathematical_program.h, line 661 at r3](https://reviewable.io:443/reviews/soonho-tri/drake/16#-KmbCRR4RS9R8IKR4Uwa:-KmbCRR4RS9R8IKR4Uwb:b-91hhr0) ([raw file](https://github.com/soonho-tri/drake/blob/9e9768e39a554e34316b6f8d155d4d083404fda7/drake/solvers/mathematical_program.h#L661)):*
> ```objc
>   // TODO(FischerGundlach) Add documentation incl. an example with list
>   // initialization and implicit conversion variable->variables
>   std::pair<symbolic::Polynomial, MatrixXDecisionVariable> NewSosPolynomial(
> ```

`NewSOSPolynomial`? `Sos`->`SOS`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/soonho-tri/drake/16#-:-KmbDad7Pu5D6PopgDsv:b-vv2shf)*

**Comment by soonho-tri** [comment]
Review status: 1 of 8 files reviewed at latest revision, 10 unresolved discussions.

---

*[drake/common/symbolic_polynomial.h, line 48 at r3](https://reviewable.io:443/reviews/soonho-tri/drake/16#-KmbALTJXbOk27La8gIk:-KmbI3MeQFZFlV-P3Ugi:b-896fix) ([raw file](https://github.com/soonho-tri/drake/blob/9e9768e39a554e34316b6f8d155d4d083404fda7/drake/common/symbolic_polynomial.h#L48)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Add a TODO here, that we will implement `int Degree(const Variables& vars)`, which returns the degrees for the  specified variables?
</blockquote></details>

Done.

---

*[drake/common/symbolic_polynomial.h, line 111 at r3](https://reviewable.io:443/reviews/soonho-tri/drake/16#-KmbAtc9ERGfc51RlkrN:-KmbHIDZVT62irNT0A2c:b-177a64) ([raw file](https://github.com/soonho-tri/drake/blob/9e9768e39a554e34316b6f8d155d4d083404fda7/drake/common/symbolic_polynomial.h#L111)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

variable * monomial should return a monomial instead of a polynomial?
</blockquote></details>

Done. (Changed and moved to `monomial.h`) Thanks for catching it!

---

*[drake/solvers/mathematical_program.cc, line 240 at r3](https://reviewable.io:443/reviews/soonho-tri/drake/16#-KmbDL9OSEElz99leDU0:-KmbHHC97WELszlgoZX7:b-896fix) ([raw file](https://github.com/soonho-tri/drake/blob/9e9768e39a554e34316b6f8d155d4d083404fda7/drake/solvers/mathematical_program.cc#L240)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Capital `X` would mean a matrix to mean, maybe use lower case `x`？
</blockquote></details>

Done.

---

*[drake/solvers/mathematical_program.h, line 653 at r3](https://reviewable.io:443/reviews/soonho-tri/drake/16#-KmbBkqAoA-6kiJm1hEc:-KmbK38uhRfFiv5ZT9zO:bfw8std) ([raw file](https://github.com/soonho-tri/drake/blob/9e9768e39a554e34316b6f8d155d4d083404fda7/drake/solvers/mathematical_program.h#L653)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

The difference between `symbolic::Variables` and `VectorXIndeterminate` are
1. In VectorXIndeterminate, the user can define an order.
2. In VectorXIndeterminate, there can be duplicated entries.
My feeling is that we do not care about the order used in VectorXIndeterminate, and we want to avoid duplicated entries in `indeterminates`, so maybe we only keep the API with `symbolic::Variables`?
</blockquote></details>

I think we ended up with `VectorXIndeterminate ` here to be consistent with `NewSOSPolynomial` function which returns a matrix of decision variables.

My suggestion is either to keep them as they are:
```c++
std::pair<symbolic::Polynomial, VectorXDecisionVariable> NewFreePolynomial(...);
std::pair<symbolic::Polynomial, MatrixXDecisionVariable> NewSosPolynomial(...);
```

or change them to be:
```c++
symbolic::Polynomial NewFreePolynomial(...);
std::pair<symbolic::Polynomial, MatrixXDecisionVariable> NewSosPolynomial(...);  // <- not changed.
```
Please note that `p.decision_variables()` returns a set of decision variables (of type `Variables`).

---

*[drake/solvers/mathematical_program.h, line 661 at r3](https://reviewable.io:443/reviews/soonho-tri/drake/16#-KmbCRR4RS9R8IKR4Uwa:-KmbH_9AhHfB8Uqo8Lec:b-4fum60) ([raw file](https://github.com/soonho-tri/drake/blob/9e9768e39a554e34316b6f8d155d4d083404fda7/drake/solvers/mathematical_program.h#L661)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

`NewSOSPolynomial`? `Sos`->`SOS`.
</blockquote></details>

I think `Sos` is actually correct according to our naming policy? For example, we have `PidControlledSystem` not `PIDControlledSystem` in Drake.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/soonho-tri/drake/16)*

**Comment by hongkai-dai** [comment]
Is there a plan to add a test in this PR? A simple SOS test could be

Prove that `2*x^4 + 2*x^3*y-x^2y^2+5*y^4` is a sum-of-squares polynomial.

The test code can be
```C++
MathematicalProgram prog;
auto x = prog.NewIndeterminates<2>();
Polynomial p(2*pow(x(0), 4) + 2 * pow(x(0), 3) * x(1) - pow(x(0), 2)*pow(x(1), 2) + 5 * pow(x(1), 4, x);
prog.AddSosConstraint(p);

auto result = prog.Solve();
EXPECT_EQ(result, SolutionResult::kSolutionFound);
```

---

Review status: 1 of 8 files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/solvers/mathematical_program.cc, line 242 at r3](https://reviewable.io:443/reviews/soonho-tri/drake/16#-KmbSbmYcxx7OYjctbHR:-KmbSbmYcxx7OYjctbHS:b-bcma2r) ([raw file](https://github.com/soonho-tri/drake/blob/9e9768e39a554e34316b6f8d155d4d083404fda7/drake/solvers/mathematical_program.cc#L242)):*
> ```cpp
>   const drake::VectorX<symbolic::Monomial> X{
>       MonomialBasis(indeterminates, degree)};
>   const MatrixXDecisionVariable Q{NewSymmetricContinuousVariables(X.size())};
> ```

I think we should add the `Q is psd` constraint inside this function. Otherwise the polynomial `p` is not SOS.

---

*[drake/solvers/mathematical_program.cc, line 683 at r3](https://reviewable.io:443/reviews/soonho-tri/drake/16#-KmbSjtkJgOl8LHAKe-_:-KmbSjtkJgOl8LHAKe-a:b-2hs4uk) ([raw file](https://github.com/soonho-tri/drake/blob/9e9768e39a554e34316b6f8d155d4d083404fda7/drake/solvers/mathematical_program.cc#L683)):*
> ```cpp
>   const MatrixXDecisionVariable& Q{p.second};
> 
>   const auto psd_binding = AddPositiveSemidefiniteConstraint(Q);
> ```

I think we should move this `psd_binding` inside `NewSosPolynomial`.

---

*[drake/solvers/mathematical_program.h, line 653 at r3](https://reviewable.io:443/reviews/soonho-tri/drake/16#-KmbBkqAoA-6kiJm1hEc:-KmbTl9-geWB_gRbHvaA:b1n7wef) ([raw file](https://github.com/soonho-tri/drake/blob/9e9768e39a554e34316b6f8d155d4d083404fda7/drake/solvers/mathematical_program.h#L653)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I think we ended up with `VectorXIndeterminate ` here to be consistent with `NewSOSPolynomial` function which returns a matrix of decision variables.

My suggestion is either to keep them as they are:
```c++
std::pair<symbolic::Polynomial, VectorXDecisionVariable> NewFreePolynomial(...);
std::pair<symbolic::Polynomial, MatrixXDecisionVariable> NewSosPolynomial(...);
```

or change them to be:
```c++
symbolic::Polynomial NewFreePolynomial(...);
std::pair<symbolic::Polynomial, MatrixXDecisionVariable> NewSosPolynomial(...);  // <- not changed.
```
Please note that `p.decision_variables()` returns a set of decision variables (of type `Variables`).
</blockquote></details>

Sorry for the confusion, I do not mean the `VectorXDecisionVariable` in the return argument, but the `VectorXIndeterminates` in the input argument. I feel we should just keep the function API
```C++
std::pair<symbolic::Polynomial, VectorXDecisionVariable> NewFreePolynomial(
      const symbolic::Variables& indeterminates, int degree);
```
but delete the API
```C++
std::pair<symbolic::Polynomial, VectorXDecisionVariable> NewFreePolynomial(
      const VectorXIndeterminate& indeterminates, int degree);
```
Namely using `symbolic::Variables` in the input is more correct than the `VectorXIndeterminate`, as it means there is no duplicated entries in `indeterminates`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/soonho-tri/drake/16#-:-KmbUP6FpiIIcSHE0K0h:b-5gcx1l)*

**Comment by moritzkuhne** [comment]
Review status: 1 of 8 files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/solvers/mathematical_program.h, line 653 at r3](https://reviewable.io:443/reviews/soonho-tri/drake/16#-KmbBkqAoA-6kiJm1hEc:-KmbUwL9VPy4sO9Xrza-:bip4xuc) ([raw file](https://github.com/soonho-tri/drake/blob/9e9768e39a554e34316b6f8d155d4d083404fda7/drake/solvers/mathematical_program.h#L653)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I think we ended up with `VectorXIndeterminate ` here to be consistent with `NewSOSPolynomial` function which returns a matrix of decision variables.

My suggestion is either to keep them as they are:
```c++
std::pair<symbolic::Polynomial, VectorXDecisionVariable> NewFreePolynomial(...);
std::pair<symbolic::Polynomial, MatrixXDecisionVariable> NewSosPolynomial(...);
```

or change them to be:
```c++
symbolic::Polynomial NewFreePolynomial(...);
std::pair<symbolic::Polynomial, MatrixXDecisionVariable> NewSosPolynomial(...);  // <- not changed.
```
Please note that `p.decision_variables()` returns a set of decision variables (of type `Variables`).
</blockquote></details>

I think we can not have duplicates in the `VectorXIndeterminate`. There is somewhere the ` static never_destroyed<atomic<Id>> next_id(1);`, users can only use the API to ask for more decision variables and therefore can no smuggle additional ones in. 

My idea for the signature was, that our getter functions themselves return the type `VectorX`. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/soonho-tri/drake/16)*

**Comment by moritzkuhne** [comment]
Review status: 1 of 8 files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/solvers/mathematical_program.h, line 653 at r3](https://reviewable.io:443/reviews/soonho-tri/drake/16#-KmbBkqAoA-6kiJm1hEc:-KmbW8bhlwPcyQaIediC:bghtl9b) ([raw file](https://github.com/soonho-tri/drake/blob/9e9768e39a554e34316b6f8d155d4d083404fda7/drake/solvers/mathematical_program.h#L653)):*
<details><summary><i>Previously, FischerGundlach wrote…</i></summary><blockquote>

I think we can not have duplicates in the `VectorXIndeterminate`. There is somewhere the ` static never_destroyed<atomic<Id>> next_id(1);`, users can only use the API to ask for more decision variables and therefore can no smuggle additional ones in. 

My idea for the signature was, that our getter functions themselves return the type `VectorX`. 
</blockquote></details>

*`decision_variable` =  `indeterminate` (though I think they share the counter anyway. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/soonho-tri/drake/16)*

**Comment by hongkai-dai** [comment]
Review status: 1 of 8 files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/solvers/mathematical_program.h, line 653 at r3](https://reviewable.io:443/reviews/soonho-tri/drake/16#-KmbBkqAoA-6kiJm1hEc:-KmbWS7B461c5jse7joK:ba4i97s) ([raw file](https://github.com/soonho-tri/drake/blob/9e9768e39a554e34316b6f8d155d4d083404fda7/drake/solvers/mathematical_program.h#L653)):*
> I think we can not have duplicates in the VectorXIndeterminate.

But the user can re-construct a `VectorXIndeterminate` with duplicated entries, for example
```C++
auto x = prog.NewIndeterminates<3>();
VectorIndeterminates<3> y(x(0), x(1), x(1)); // Note that x(1) is duplicated in y.
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/soonho-tri/drake/16)*

**Comment by soonho-tri** [comment]
Thanks, I'll add it and merge only if it passes.

---

Review status: 1 of 8 files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/solvers/mathematical_program.cc, line 242 at r3](https://reviewable.io:443/reviews/soonho-tri/drake/16#-KmbSbmYcxx7OYjctbHR:-KmbXqTEWBLeZ3ZwKq7v:b-ysigur) ([raw file](https://github.com/soonho-tri/drake/blob/9e9768e39a554e34316b6f8d155d4d083404fda7/drake/solvers/mathematical_program.cc#L242)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I think we should add the `Q is psd` constraint inside this function. Otherwise the polynomial `p` is not SOS.
</blockquote></details>

I see. I was wondering about that, but don't we have to return the PSD binding from this function then?

---

*[drake/solvers/mathematical_program.h, line 653 at r3](https://reviewable.io:443/reviews/soonho-tri/drake/16#-KmbBkqAoA-6kiJm1hEc:-KmbY51UwN2q04ZQF2N8:bzh4e0p) ([raw file](https://github.com/soonho-tri/drake/blob/9e9768e39a554e34316b6f8d155d4d083404fda7/drake/solvers/mathematical_program.h#L653)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

> I think we can not have duplicates in the VectorXIndeterminate.

But the user can re-construct a `VectorXIndeterminate` with duplicated entries, for example
```C++
auto x = prog.NewIndeterminates<3>();
VectorIndeterminates<3> y(x(0), x(1), x(1)); // Note that x(1) is duplicated in y.
```
</blockquote></details>

@fischergundlach , we can have duplicates in `VectorXIndeterminate`.

I think it's good to remove the ones taking `VectorXIndeterminate` and leave the ones taking `Variables`.

For the usability, I'll add a constructor in `symbolic::Variables` class taking a matrix of `symbolic::Variable`s.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/soonho-tri/drake/16#-:-KmbXi5z_YeGQoYTTcyf:b-rqflw0)*

**Comment by moritzkuhne** [comment]
Review status: 1 of 8 files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/solvers/mathematical_program.h, line 653 at r3](https://reviewable.io:443/reviews/soonho-tri/drake/16#-KmbBkqAoA-6kiJm1hEc:-KmbXivyWG7hJGq-oBeM:bb6mt9b) ([raw file](https://github.com/soonho-tri/drake/blob/9e9768e39a554e34316b6f8d155d4d083404fda7/drake/solvers/mathematical_program.h#L653)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

@fischergundlach , we can have duplicates in `VectorXIndeterminate`.

I think it's good to remove the ones taking `VectorXIndeterminate` and leave the ones taking `Variables`.

For the usability, I'll add a constructor in `symbolic::Variables` class taking a matrix of `symbolic::Variable`s.

</blockquote></details>

:+1:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/soonho-tri/drake/16)*

**Comment by soonho-tri** [comment]
Review status: 0 of 9 files reviewed at latest revision, 8 unresolved discussions.

---

*[drake/solvers/mathematical_program.cc, line 242 at r3](https://reviewable.io:443/reviews/soonho-tri/drake/16#-KmbSbmYcxx7OYjctbHR:-KmbcOVW16V9Z47zv6cF:b-896fix) ([raw file](https://github.com/soonho-tri/drake/blob/9e9768e39a554e34316b6f8d155d4d083404fda7/drake/solvers/mathematical_program.cc#L242)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

I see. I was wondering about that, but don't we have to return the PSD binding from this function then?
</blockquote></details>

Done.

---

*[drake/solvers/mathematical_program.cc, line 683 at r3](https://reviewable.io:443/reviews/soonho-tri/drake/16#-KmbSjtkJgOl8LHAKe-_:-KmbbXE3gbgHXot9Xwz3:b-896fix) ([raw file](https://github.com/soonho-tri/drake/blob/9e9768e39a554e34316b6f8d155d4d083404fda7/drake/solvers/mathematical_program.cc#L683)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I think we should move this `psd_binding` inside `NewSosPolynomial`.
</blockquote></details>

Done.

---

*[drake/solvers/mathematical_program.h, line 653 at r3](https://reviewable.io:443/reviews/soonho-tri/drake/16#-KmbBkqAoA-6kiJm1hEc:-KmbcREH472mBqvzRPEV:bbobg3j) ([raw file](https://github.com/soonho-tri/drake/blob/9e9768e39a554e34316b6f8d155d4d083404fda7/drake/solvers/mathematical_program.h#L653)):*
> I think it's good to remove the ones taking VectorXIndeterminate and leave the ones taking Variables.

Done.

> For the usability, I'll add a constructor in symbolic::Variables class taking a matrix of symbolic::Variables.

Will do in another PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/soonho-tri/drake/16)*

**Comment by soonho-tri** [comment]
Tests added/passed. To run it, please do:

```
bazel test //drake/solvers:sos_constraint_test --config=mosek
```

---

Review status: 0 of 9 files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/soonho-tri/drake/16#-:-KmbnZ2YAeiOs1JmqFT6:b-szxlh)*

**Pull request merged**
